# Generated by Django 2.2 on 2019-04-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_lmgtfy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='lmgtfy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
